import Head from 'next/head';

import Hero from '@/components/landing/Hero';
import Header from '@/components/landing/Header';
import Skills from '@/components/landing/Skills';
import Divider from '@/components/landing/Divider';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />

        <Hero />
        <Divider />
        <Skills />
        <Divider />
      </main>
    </>
  );
}
